### ISSUE TITLE
Correct local installation instructions

### ISSUE THREAD

**Issue by davidbgk** [MattiSG/Watai#130] opened 2015-09-09 14:04 UTC
After a `npm install watai`, the `go` file is not present in the `/node_modules/watai/` directory. It probably has to do with the `package.json•files` property but I'm not used to JS packaging.

**Comment by davidbgk** [comment] 2015-09-09 14:07
I confirm that once the file is created and `chmod +x`ed the `--installed` check returns the encouraging message :)

**Comment by MattiSG** [comment] 2015-09-10 09:45
Did you follow the “local install” procedure?

**Comment by davidbgk** [comment] 2015-09-10 12:20
Yes, [that one](https://github.com/MattiSG/Watai#local-install).

**Comment by MattiSG** [comment] 2015-09-10 14:38
Then I think the problem is simply that the doc is not up-to-date and dates from the time before NPM symlinked the binaries to `.bin` (or at least, before I knew it did). The solution is to update the README so that the suggested alias is `node_modules/.bin/watai`.

**Comment by davidbgk** [comment] 2015-09-11 11:24
Agreed, `watai` executable is present in my `.bin` folder.

**Comment by MattiSG** [comment] 2015-09-12 14:34
Fixed in 2d0f48f164ecaaca85f5d60bcb8ecbe897d6c5eb

**Closed by MattiSG** 2015-09-12 14:34 UTC
Labels: documentation
